# Auto Generated Dockerfile

FROM ballerina/ballerina-runtime:0.991.0
LABEL maintainer="dev@ballerina.io"

COPY microservice-visualiserpanorama.balx /home/ballerina 

EXPOSE  9095
CMD ballerina run  microservice-visualiserpanorama.balx
