#######################################
# Microservice getuserinfos           #
#######################################
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ballerina-getuser
  name: ballerina-getuser
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9091
  selector:
    app: ballerina-getuser
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ballerina-getuser
  labels:
    app: ballerina-getuser
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ballerina-getuser
      version: v1
  template:
    metadata:
      labels:
        app: ballerina-getuser
        version: v1
    spec:
      containers:
      - name: ballerina-getuser
        image: samihoss/ballerina-userinfos:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9091
---