# Auto Generated Dockerfile

FROM ballerina/ballerina-runtime:0.991.0
LABEL maintainer="dev@ballerina.io"

COPY microservice-ctgdata.balx /home/ballerina 

EXPOSE  9093
CMD ballerina run  microservice-ctgdata.balx
