# Auto Generated Dockerfile

FROM ballerina/ballerina-runtime:0.991.0
LABEL maintainer="dev@ballerina.io"

COPY microservice-panoramaglobal.balx /home/ballerina 

EXPOSE  9097
CMD ballerina run  microservice-panoramaglobal.balx
