# Auto Generated Dockerfile

FROM ballerina/ballerina-runtime:0.991.0
LABEL maintainer="dev@ballerina.io"

COPY microservice-wsaccount.balx /home/ballerina 

EXPOSE  9096
CMD ballerina run  microservice-wsaccount.balx
