# Auto Generated Dockerfile

FROM ballerina/ballerina-runtime:0.991.0
LABEL maintainer="dev@ballerina.io"

COPY microservice-getuser.balx /home/ballerina 

EXPOSE  9091
CMD ballerina run  microservice-getuser.balx
