# Auto Generated Dockerfile

FROM ballerina/ballerina-runtime:0.991.0
LABEL maintainer="dev@ballerina.io"

COPY microservice-composition.balx /home/ballerina 

EXPOSE  9094
CMD ballerina run  microservice-composition.balx
