# Auto Generated Dockerfile

FROM ballerina/ballerina-runtime:0.991.0
LABEL maintainer="dev@ballerina.io"

COPY microservice-getdossier.balx /home/ballerina 

EXPOSE  9092
CMD ballerina run  microservice-getdossier.balx
